#TODO: Print a title line for your story
#TODO: Print 4 story lines(one per print)
#TODO: Print an ending line like "THE END"
print("--- About me ---")
print("ZERO TO HIRED DATA ENGINEER")
print("My name is Cristian, and in 6 months from now I will land a job as a junior data engineer")
print("Today is Monday, Feb 16th 2026")
print("I will land a job before my birthday, in August")
print("I'm from Romania, and I moved to Moscow,Russia 2 years ago.Before Moscow, I lived in California.")
print("Decided to learn data engineering last year, but never really started. I am all in starting today. Will aim for 4-6 hours of learning/day")
print("Follow along if you want to learn data engineering! I am starting with completely 0 CS or coding experience, so I will take it slow, starting with fundamentals.")
print("THE END")

print("\n")
print("Rules of python")
print("1.String literals have to always be between quotes. Never forget to close them or you will get a runtime error")
print("2.Comments start with # and they are used to explain code")
print("3.Syntax errors don't let you run the program. It doesn't even start because the grammar is broken, while runtime error runs the program but finds an error while running")
print("4.You should only write git init once per project.")
print("5.print() is a Python instruction and what is between paranthesis is an argument - in today's case, a string literal")
